/**
 * @describe  存放mutation名称常量 注：按module分代码块
 * @example
 */

// 设置当前组件
export const SET_CURRENT_COMPONENT = 'SET_CURRENT_COMPONENT'
// 设置组件数据集
export const ADD_COMPONENTS = 'ADD_COMPONENTS'
// 添加当前组件
export const SET_COMPONENTS_ITEM = 'SET_COMPONENTS_ITEM'
// 设置当前数据
export const SET_COMPONENTS_DATA = 'SET_COMPONENTS_DATA'
// 改变组件顺序
export const SORT_COMPONENTS_GLOBEL = 'SORT_COMPONENTS_GLOBEL'

// 添加提示组件
export const ADD_COMPONNET_HOLDER_GLOBEL = 'ADD_COMPONNET_HOLDER_GLOBEL'

// 删除提示组件
export const DEL_COMPONNET_HOLDER_GLOBEL = 'DEL_COMPONNET_HOLDER_GLOBEL'

// 删除并暂存当前拖拽组件
export const DEL_AND_ADD_COMPONNET_TO_TEMPLIST_GLOBEL = 'DEL_AND_ADD_COMPONNET_TO_TEMPLIST_GLOBEL'

// 回收组件到trash
export const RECYCLE_COMPONNET_GLOBEL = 'RECYCLE_COMPONNET_GLOBEL'

// 显示工具栏
export const SHOW_TOOL_BAR_GLOBEL = 'SHOW_TOOL_BAR_GLOBEL'

// 隐藏工具栏
export const HIDE_TOOL_BAR_GLOBEL = 'HIDE_TOOL_BAR_GLOBEL'

// 移动组件
export const MOVE_COMPONNET_GLOBEL = 'MOVE_COMPONNET_GLOBEL'

// 删除组件
export const DEL_COMPONNET_GLOBEL = 'DLE_COMPONNET_GLOBEL'


